server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guiche
    username: postgres
    password: sua_senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092

  consumer:
    group-id: painel-group
    auto-offset-reset: earliest
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  listener:
    missing-topics-fatal: false
